[package]
name = "ynab-rs"
version = "0.1.0"
authors = ["jwmurray <john@gardenway.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "*"
json = "*"
